---

# - name: remove mariadb
#   become: yes
#   yum: name=mariadb-libs state=removed

- name: install mysql original repository
  sudo: yes
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- name: install mysql
  become: yes
  yum: name={{ item }} state=installed enablerepo=mysql56-community
  with_items:
    - mysql-community-common
    - mysql-community-devel
    - mysql-community-libs
    - mysql-community-server
    - MySQL-python

- name: reconfigure my.cnf
  become: yes
  template: src=my.cnf dest=/etc/my.cnf owner=mysql group=mysql mode=0644

- name: create log file
  become: yes
  file: path=/var/log/mysqld-slow.log group=mysql owner=mysql state=touch mode=0755

- name: mysql restart and enable
  become: yes
  service: name=mysqld state=restarted enabled=yes
