---

- name: install nginx
  become: yes
  yum: name="{{ item }}" state=present enablerepo=epel
  with_items:
    - nginx

- name: reconfigure nginx.conf
  become: yes
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

- name: reconfigure conf.d/api.conf
  become: yes
  template: src=api.conf dest=/etc/nginx/conf.d/api.conf owner=root group=root mode=0644

- name: remove conf.d/default.conf
  become: yes
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: nginx restart and enable
  become: yes
  service: name=nginx state=restarted enabled=yes
